### ISSUE TITLE
Allow '=' chars in "any of" value sequence

### ISSUE THREAD

**Issue by bjornfor** [mkorpela/RoboMachine#11]
What do you think of allowing '=' in the "any of" value sequence? RF itself allows '=' withing variables.

**Comment by mkorpela** [comment]
Sounds good! Patches are welcome :D

**Comment by bjornfor** [comment]
Great, you're alive! See https://github.com/mkorpela/RoboMachine/pull/13.

**Comment by mkorpela** [comment]
Yeah, I was travelling in Sicily for the previous week so didn't use much time to check github.
