### ISSUE TITLE
Allow comments in *** Machine *** table

### ISSUE THREAD

**Issue by bjornfor** [mkorpela/RoboMachine#12]
Commenting out a line in the Machine table cause error:

```
Exception at line 10
Expected Re:('\\w+( \\w+)*')
```

It'd be nice to allow comments there.

**Comment by bjornfor** [comment]
Oh, I see that comments are supported, but apparently not in the first lines of the Machine table, where one defines the "any of" stuff.

**Comment by mkorpela** [comment]
Thanks for interest in this small lib!
I've not worked on it for a while - the parsing library is a picky.
If you want to contribute and fix the issue, I'll be more than happy to merge your contribution!

**Comment by mkorpela** [comment]
By the way if you are interested in online MBT then https://github.com/mkorpela/OnlineRoboMachine might be more interesting experiment. It uses random walk but it is fully functional .. although docs are not.

**Comment by bjornfor** [comment]
Thanks, I'll check it out.

**Comment by bjornfor** [comment]
Interesting! Thanks for pointing it out.

**Comment by bjornfor** [comment]
Fixed by https://github.com/bjornfor/RoboMachine/commit/41295aaf6700c376b30ace79e20a9bda366f7eb6.

**Comment by bjornfor** [comment]
Oops, I mean https://github.com/mkorpela/RoboMachine/commit/41295aaf6700c376b30ace79e20a9bda366f7eb6. (Same commit though.)
