### ISSUE TITLE
Full boolean logic support in constraints and rules

### ISSUE THREAD

**Issue by mkorpela** [mkorpela/RoboMachine#3]

**Comment by bjornfor** [comment]
This seems very useful to me. (Why did you close it?)

**Comment by bjornfor** [comment]
I'm thinking of less-than and greater-than operators.

**Comment by bjornfor** [comment]
Well actually, I also have a use case for full python expressions in the constraints section (exprs that evaluate to boolean values). Do you have any thoughts on that?

**Comment by bjornfor** [comment]
I have WIP branch with new operators: <, <=, >, >=. I'm thinking of adding support for ```${VAR} (not) in (1,4,9)``` too. Thoughts?
